---
- name: Restart {{ service }} service
  hosts: "{{ host }}"
  become: yes

  tasks:
    - name: Ensure {{ service }} service is running
      systemd:
        name: "{{ service }}"
        state: started
      ignore_errors: yes

    - name: Restart {{ service }} service
      systemd:
        name: "{{ service }}"
        state: restarted
